### ISSUE TITLE
Add to share intent

### ISSUE THREAD

**Issue by RedAuburn** [iyox-studios/iyox-Wormhole#1]
thank you for the fantastic fork! :)

it'd be nice if wormhole was displayed as an option in the share intent menu:

(see https://developer.android.com/training/sharing/receive)
![Screenshot_20240226-133731_IntentResolver](https://github.com/iyox-studios/iyox-Wormhole/assets/26939824/a166fb7a-48a8-40d0-b59c-66d71c3c57a4)

**Comment by EwuUwe** [comment]
Thanks for the interest in the app! I kinda forgot about this feature, but it is obviously essential. I'll look into it and keep you posted on the progress. Appreciate your input!
