### ISSUE TITLE
[BUG] Word count limits

### ISSUE THREAD

**Issue by PhilippKosarev** [iyox-studios/iyox-Wormhole#12]
Hey there, thank you for the app!

There does not appear to be a lower or an upper limit on the word count settings. Also maybe a slider instead of a text input field would be a bit simpler to use.
![iyox_example](https://github.com/iyox-studios/iyox-Wormhole/assets/102914158/53708fe4-c7cf-4e43-a10f-48a0ffbfe2bc)

**Comment by EwuUwe** [comment]
Hi, thank you very much for your input! I think a slider would be a great idea, I'll get to work on that soon
