### ISSUE TITLE
Wrong APK at latest release

### ISSUE THREAD

**Issue by IzzySoft** [iyox-studios/iyox-Wormhole#18]
at v0.1.6 you accidentally attached an APK signed with a debug key:

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: eb1a9319a6eb2344ba85b04b52cc886af92fe30fd8a20558d8eafd322a0c3516
Signer #1 certificate SHA-1 digest: 83d8016a6e02e987f4f2f8bfc3ed8637f2e3a5a1
Signer #1 certificate MD5 digest: a537605b0f00e9fe720de73d3ec59467
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

added to that, it also uses the wrong version:

    package: name='com.iyox.wormhole' versionCode='2027' versionName='0.1.5'

Could you please replace that with the correct APK? Thanks in advance!

**Comment by IzzySoft** [comment]
:hankey: happens – thanks for the instant fix! All fine now again, v0.1.6 should show up in my repo with the next sync around 7 pm UTC and update check is re-enabled.

**Comment by TotallyAvailable** [comment]
My "usual" case description whenever an old version (based on date) is pushed back to the top in your repo (v0.2.5 from 17.08.25) as it is obviously easy enough to "verify" the underlying issue...by now I don't even need a back and forth with the dev anymore to figure it out, given how common the split-to-versioncode downgrade is (leaving all existing users stranded again).

Given that there's no universal version available, the only users unaffected are those on the play store... re-install or wait for big version (code) bump for the rest. On top of new users based on the recent RB based F-Droid inclusion eventually ending up at v0.2.5 again.

**Comment by UjuiUjuMandan** [comment]
> which usually means "use whatever is latest at this moment"

I saw nix installed 3.27.4 at this repo, I suppose it will respect pubspec.yaml?

https://github.com/iyox-studios/iyox-Wormhole/actions/runs/23385791435/job/68032522950#step:5:611

**Comment by IzzySoft** [comment]
I don't know what tools *respect* that, sorry – I'm no Flutter dev. We're using it to keep the version in sync between the developers' builds and ours. To my knowledge, it's not a binding definition there; if a different Flutter version is installed, that would be the one used. If you have some automation (like, Github actions), you have to _tell them_ to honor it, via their configuration, so they **install** the defined version.
